

spring:
  datasource:
    url: jdbc:mysql://localhost/dev?serverTimezone=UTC
    username: root
    password: 1234

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 257682517799-8kk5eqd246q6vmc7ei5sicu3p37kpllk.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create